services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: lingo
      POSTGRES_PASSWORD: lingopass
      POSTGRES_DB: lingolink_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    mem_limit: 256m

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://lingo:lingopass@postgres:5432/lingolink_db
      OMP_NUM_THREADS: "2"
      MKL_NUM_THREADS: "2"
      TOKENIZERS_PARALLELISM: "false"
      OPENBLAS_NUM_THREADS: "2"
      HF_HOME: "/hf_cache"
      TRANSFORMERS_CACHE: "/hf_cache"
      XDG_CACHE_HOME: "/hf_cache"
    depends_on:
      - postgres
    volumes:
      - ./data:/app/data
      - ./backend/app:/app/app
      - ./hf_cache:/hf_cache
    mem_limit: 5g
    shm_size: 512m
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

volumes:
  pgdata: