name: lingolink_mobile
description: "LingoLink AI - Push-to-talk voice translator"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  record: ^6.1.1
  just_audio: ^0.9.42
  web_socket_channel: ^3.0.1
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true